import * as THREE from "three";
import React, { useRef, useState } from "react";
import TextSphere from "./textSphere";
import lerp from "lerp";
import { useLoader, useFrame } from "react-three-fiber";
import "./shaders/hb";
import "./shaders/hb2";
import "./shaders/hb3";

export default function HB({ img, speed }) {
  const mesh = useRef();
  const geometry = useRef();
  const hb = useRef();
  const hb2 = useRef();
  const hb3 = useRef();
  const texture1 = useLoader(THREE.TextureLoader, img);

  useFrame(({ clock }) => {
    // hb.current.time = clock.elapsedTime;
    // hb2.current.time = clock.elapsedTime;
    hb3.current.time = clock.elapsedTime;
  });

  return (
    <>
      <TextSphere>
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAYHAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAYHAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAYHAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAYHAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
        HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY
        BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY HAPPY BIRTHDAY
      </TextSphere>
      {/* <mesh ref={mesh} scale={[0.035, 0.035, 0.035]} position={[-4, -2, 0]}>
        <planeGeometry ref={geometry} attach="geometry" args={[100, 100]} />
        <hb ref={hb} attach="material" texture={texture1} toneMapped={false} />
      </mesh>
      <mesh ref={mesh} scale={[0.035, 0.035, 0.035]} position={[0, -2, 0]}>
        <planeGeometry ref={geometry} attach="geometry" args={[100, 100]} />
        <hb2
          ref={hb2}
          attach="material"
          texture={texture1}
          toneMapped={false}
        />
      </mesh> */}
      <mesh ref={mesh} scale={[0.75, 0.7, 0.7]} position={[0, 0, -4]}>
        <planeGeometry ref={geometry} attach="geometry" args={[100, 100]} />
        <hb3
          ref={hb3}
          attach="material"
          texture={texture1}
          toneMapped={false}
        />
      </mesh>
    </>
  );
}
